name: Deploy to GitHub Page - Dev

on:
  push:
    branches:    
      - dev

jobs:
  build-and-push:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        node-version: 12.13.1 
    - name: Dependencies install
      run: |
        npm install -g hexo-cli
        npm install
    - name: Generate Hexo
      run: |
        hexo g
    - name: Push to GitHub Page
      run: |
        cd public
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        git init
        git remote add origin https://${{ secrets.PAT }}@github.com/${{ secrets.GIT_REPO_URL }}.git
        git add .
        git commit -m "Update"
        git push origin master --force
